repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.1
    hooks:
      - id: mypy
        additional_dependencies: [types-setuptools]
        pass_filenames: false
        args: ["--config-file=pyproject.toml", "smartclip"]
        files: ^smartclip/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: uv-ruff-format
        name: uv ruff format
        entry: uv
        language: system
        pass_filenames: true
        types: [python]
        args: ["run", "ruff", "format", "--force-exclude"]
